[green_agent]
image = "ghcr.io/cdavm/green-debate-judge:v1.0"
env = { API_KEY = "${GITHUB_SECRET_NAME}", GOOGLE_API_KEY = "${GOOGLE_API_KEY}", LOG_LEVEL = "INFO" }

[[participants]]
agentbeats_id = "019ac01a-928e-7840-9c4c-b94f9131a355"
name = "pro_debater"
image = "ghcr.io/cdavm/purple-debate-pro:v1.0"
env = {}

[[participants]]
agentbeats_id = "019ac01a-cbb2-7a83-9719-3be38951187b"
name = "con_debater"
image = "ghcr.io/cdavm/purple-debate-con:v1.0"
env = {}

[config]
topic = "Should houses have steeper roofs or not?"
num_rounds = 2
