[green_agent]
image = "ghcr.io/cdavm/green-debate-judge:v1.0"
env = { API_KEY = "${GITHUB_SECRET_NAME}", LOG_LEVEL = "INFO" }

[[participants]]
agentbeats_id = ""
name = "debater_pro"
image = ""
env = {}

[[participants]]
agentbeats_id = ""
name = "debater_con"
image = ""
env = {}

[config]
# Add your assessment config here
